spring:
  application:
    name: msr-log-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/msrlog?createDatabaseIfNotExist=true&allowPublicKeyRetieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: root
    password: mysql